export const KuotaPaketData = {
    'Axiata Axis': {
      packages: [
        {
          nama: 'BRONET 24Jam, 1GB, 7 hari',
          hargaBaru: '12.100',
          hargaLama: '12.490',
          diskon: '3',
          kode: 'sbiaxisdata1gb',
        },
        {
          nama: 'BRONET 24Jam, 2GB, 30 hari',
          hargaBaru: '22.530',
          hargaLama: '23.250',
          diskon: '3',
          kode: 'sbiaxisdata2gb',
        },
        {
          nama: '2GB Kuota Utama + 6GB 4G. Masa aktif 30 hari',
          hargaBaru: '1.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbiaxisdataOM8',
        },
        {
          nama: 'BRONET 24Jam 5GB, 30 hari',
          hargaBaru: '1.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbiaxisdata5gb',
        },
        {
          nama: '3GB Kuota Utama + 9GB 4G. Masa aktif 30 hari',
          hargaBaru: '1.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbiaxisdataOM12',
        },
      ],
    },
    'Indosat': {
      packages: [
        {
          nama: 'KUOTA 1GB 30 hari',
          hargaBaru: '1.000',
          hargaLama: '10.000',
          diskon: '90',
          kode: 'sbiisatdata1gb',
        },
        {
          nama: 'KUOTA 2GB 30 hari',
          hargaBaru: '1.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbiisatdata2gb',
        },
        {
          nama: 'KUOTA 4GB 30 hari',
          hargaBaru: '1.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbiisatdata4gb',
        },
        {
          nama: 'Kuota 12GB berlaku selama 30 hari (24 jam)',
          hargaBaru: '1.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbiisatdata12gb',
        },
        {
          nama: 'KUOTA 5GB 30 hari',
          hargaBaru: '1.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbiisatdata5gb',
        },
      ],
    },
    'Smartfren': {

      packages: [
        {
          nama: 'Unlimited 4G 7D, Batas pemakaian 1GB/hari',
          hargaBaru: '20.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbismartdataSUNL20RB',
        },
        {
          nama: 'Unlimited FUP 700MB/Hari, Masa Aktif 28 Hari',
          hargaBaru: '60.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbismartdataSUNL60RB',
        },
        {
          nama: 'Unlimited 1.5GB + 1.5GB/Day FUP, Masa aktif 28 hari',
          hargaBaru: '80.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbismartdataSUNL80RB',
        },
        {
          nama: 'Super 4G Unlimited. Unlimited 2GB/Hari, Masa Aktif 28 Hari',
          hargaBaru: '200.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbismartdataSUNL200RB',
        },
        {
          nama: 'Unlimited 1GB + 1GB/Day FUP, Masa Aktif 28 hari',
          hargaBaru: '100.000',
          hargaLama: '',
          diskon: '',
          kode: 'sbismartdataSUNL100RB',
        },
      ],
    },
    'Telkomsel': {
    packages: [
      {
        nama: '750 MB semua jaringan bebas zona, masa aktif 7 hari',
        hargaBaru: '7.500',
        hargaLama: '',
        diskon: '',
        kode: 'sbtseldata750MB',
      },
      {
        nama: '2 GB semua jaringan + bebas zona, masa aktif 30 hari',
        hargaBaru: '12.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbtseldata2GB',
      },
      {
        nama: '800MB - 1.5GB sesuai zona, masa aktif 30 hari',
        hargaBaru: '5.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbtseldata50000',
      },
      {
        nama: 'Internet 3.3GB s/d 7GB + OMG! 1GB Sesuai Zona',
        hargaBaru: '55.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbtseldataB55',
      },
      {
        nama: 'Internet 4GB s/d 13GB + OMG! 2GB Sesuai Zona',
        hargaBaru: '75.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbtseldataB75',
      },
      {
        nama: '5 GB semua jaringan + bebas zona, masa aktif 30 hari',
        hargaBaru: '50.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbtseldata5gb',
      },
      {
        nama: 'DATA FLASH 4GB Semua jaringan bebas zona',
        hargaBaru: '40.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbtseldata4gb',
      },
      {
        nama: 'DATA FLASH 8GB Semua jaringan bebas zona',
        hargaBaru: '80.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbtseldata8gb',
      },
      {
        nama: 'Telkomsel Data ORBIT 70GB. 30 Hari',
        hargaBaru: '70.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbtseldata70',
      },
      {
        nama: 'Telkomsel Data ORBIT 130GB + EXTRA Kuota 5GB. 30 Hari',
        hargaBaru: '130.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbtseldata130',
      },
    ],
  },
  'Tri': {
    packages: [
      {
        nama: 'Three Data Kuota Pure 100MB / 30 Hari',
        hargaBaru: '1.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbithreedataKP100MB',
      },
      {
        nama: 'Three Data Kuota Pure 1 GB / 30 Hari',
        hargaBaru: '10.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbithreedataKP1GB',
      },
      {
        nama: '3 GB semua jaringan 24 jam, Masa Aktif 3 Hari',
        hargaBaru: '30.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbithreedataIS3GB3D',
      },
      {
        nama: 'Three Data Kuota Pure 5 GB / 30 Hari',
        hargaBaru: '50.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbithreedataKP5GB',
      },
      {
        nama: '30GB (8GB + 22GB 4G)',
        hargaBaru: '30.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbithreedata4G30GB',
      },
    ],
  },
  'XL': {
    packages: [
      {
        nama: 'Kuota 4GB Masa aktif 7 Hari',
        hargaBaru: '1.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbixldataHR8',
      },
      {
        nama: 'Kuota 3GB Masa aktif 7 Hari',
        hargaBaru: '1.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbixldataHR5',
      },
      {
        nama: 'Kuota 1,5GB Masa aktif 30 Hari',
        hargaBaru: '1.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbixldataHR50',
      },
      {
        nama: 'Data 3GB untuk masa aktif 30 Hari',
        hargaBaru: '1.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbixldata3gb',
      },
      {
        nama: 'Data 5GB untuk masa aktif 30 Hari',
        hargaBaru: '1.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbixldata5gb',
      },
      {
        nama: 'Kuota 8GB Masa aktif 30 Hari',
        hargaBaru: '1.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbixldataHR130',
      },
      {
        nama: 'Kuota 16GB Masa aktif 30 Hari',
        hargaBaru: '1.000',
        hargaLama: '',
        diskon: '',
        kode: 'sbixldataHR220',
      },
    ],
  },
};
