export const KuotaPaketData = {
  'Axis': {
    packages: [
      {
        nama: 'BRONET 24Jam, 1GB, 7 hari',
        harga: '22.120',
        diskon: '10',
        productCode: 'sbiaxisdata1gb',
        kuota: '1GB',
        masaBerlaku: '7 hari',
      },
      {
        nama: 'BRONET 24Jam, 2GB, 30 hari',
        harga: '30.160',
        diskon: '',
        productCode: 'sbiaxisdata2gb',
        kuota: '2GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: '2GB Kuota Utama + 6GB 4G. Masa aktif 30 hari',
        harga: '54.690',
        diskon: '',
        productCode: 'sbiaxisdataOM8',
        kuota: '2GB + 6GB 4G',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'BRONET 24Jam 5GB, 30 hari',
        harga: '59.310',
        diskon: '',
        productCode: 'sbiaxisdata5gb',
        kuota: '5GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: '3GB Kuota Utama + 9GB 4G. Masa aktif 30 hari',
        harga: '69.770',
        diskon: '',
        productCode: 'sbiaxisdataOM12',
        kuota: '3GB + 9GB 4G',
        masaBerlaku: '30 hari',
      },
    ],
  },
  'Indosat': {
    packages: [
      {
        nama: 'KUOTA 1GB 30 hari',
        harga: '13.070',
        diskon: '',
        productCode: 'sbiisatdata1gb',
        kuota: '1GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'KUOTA 2GB 30 hari',
        harga: '24.630',
        diskon: '',
        productCode: 'sbiisatdata2gb',
        kuota: '2GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'KUOTA 4GB 30 hari',
        harga: '48.360',
        diskon: '',
        productCode: 'sbiisatdata4gb',
        kuota: '4GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'Kuota 12GB berlaku selama 30 hari (24 jam)',
        harga: '85.000',
        diskon: '',
        productCode: 'sbiisatdata12gb',
        kuota: '12GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'KUOTA 5GB 30 hari',
        harga: '60.220',
        diskon: '',
        productCode: 'sbiisatdata5gb',
        kuota: '5GB',
        masaBerlaku: '30 hari',
      },
    ],
  },
  'Smartfren': {
    packages: [
      {
        nama: 'Unlimited 4G 7D, Batas pemakaian 1GB/hari, Berlaku 7 hari',
        harga: '24.925',
        diskon: '',
        productCode: 'sbismartdataSUNL20RB',
        kuota: '1GB/hari',
        masaBerlaku: '7 hari',
      },
      {
        nama: 'Unlimited FUP 700MB/ Hari, Masa Aktif 28 Hari',
        harga: '64.750',
        diskon: '',
        productCode: 'sbismartdataSUNL60RB',
        kuota: '700MB/hari',
        masaBerlaku: '28 hari',
      },
      {
        nama: 'Unlimited 1.5GB + 1.5GB / Day FUP. Masa aktif 28 hari',
        harga: '99.520',
        diskon: '',
        productCode: 'sbismartdataSUNL80RB',
        kuota: '1.5GB/hari',
        masaBerlaku: '28 hari',
      },
      {
        nama: 'Super 4G Unlimited. Unlimited 2GB/ Hari. Masa Aktif 28 Hari',
        harga: '91.925',
        diskon: '',
        productCode: 'sbismartdataSUNL200RB',
        kuota: '2GB/hari',
        masaBerlaku: '28 hari',
      },
      {
        nama: 'Unlimited 1GB + 1GB / Day FUP. Masa aktif 28 hari',
        harga: '80.170',
        diskon: '',
        productCode: 'sbismartdataSUNL100RB',
        kuota: '1GB/hari',
        masaBerlaku: '28 hari',
      },
    ],
  },
  'Telkomsel': {
    packages: [
      {
        nama: '750 MB semua jaringan bebas zona, masa aktif 7 hari',
        harga: '19.610',
        diskon: '',
        productCode: 'sbtseldata750MB',
        kuota: '750MB',
        masaBerlaku: '7 hari',
      },
      {
        nama: '2 GB semua jaringan + bebas zona, masa aktif 30 hari',
        harga: '45.240',
        diskon: '',
        productCode: 'sbtseldata2GB',
        kuota: '2GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: '800MB - 1.5GB sesuai zona, masa aktif 30 hari',
        harga: '51.500',
        diskon: '',
        productCode: 'sbtseldata50000',
        kuota: '800MB - 1.5GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'Internet 3.3GB s/d 7GB + OMG! 1GB Sesuai Zona',
        harga: '55.250',
        diskon: '',
        productCode: 'sbtseldataB55',
        kuota: '3.3GB s/d 7GB + 1GB OMG',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'Internet 4GB s/d 13GB + OMG! 2GB Sesuai Zona',
        harga: '75.850',
        diskon: '',
        productCode: 'sbtseldataB75',
        kuota: '4GB s/d 13GB + 2GB OMG',
        masaBerlaku: '30 hari',
      },
      {
        nama: '5 GB semua jaringan + bebas zona, masa aktif 30 hari',
        harga: '84.190',
        diskon: '',
        productCode: 'sbtseldata5gb',
        kuota: '5GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'DATA FLASH 4GB Semua jaringan bebas zona',
        harga: '90.470',
        diskon: '',
        productCode: 'sbtseldata4gb',
        kuota: '4GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'DATA FLASH 8GB Semua jaringan bebas zona',
        harga: '140.730',
        diskon: '',
        productCode: 'sbtseldata8gb',
        kuota: '8GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'Telkomsel Data ORBIT 70GB. 30 Hari',
        harga: '131.500',
        diskon: '',
        productCode: 'sbtseldata70',
        kuota: '70GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'Telkomsel Data ORBIT 130GB + EXTRA Kuota 5GB. 30 Hari',
        harga: '205.000',
        diskon: '',
        productCode: 'sbtseldata130',
        kuota: '130GB + 5GB',
        masaBerlaku: '30 hari',
      },
    ],
  },
  'Tri': {
    packages: [
      {
        nama: 'Three Data Kuota Pure 100MB / 30 Hari',
        harga: '4.500',
        diskon: '',
        productCode: 'sbithreedataKP100MB',
        kuota: '100MB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'Three Data Kuota Pure 1 GB / 30 Hari',
        harga: '12.000',
        diskon: '',
        productCode: 'sbithreedataKP1GB',
        kuota: '1GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: '3 GB semua jaringan 24 jam, Masa Aktif 3 Hari',
        harga: '20.010',
        diskon: '',
        productCode: 'sbithreedataIS3GB3D',
        kuota: '3GB',
        masaBerlaku: '3 hari',
      },
      {
        nama: 'Three Data Kuota Pure 5 GB / 30 Hari',
        harga: '55.000',
        diskon: '',
        productCode: 'sbithreedataKP5GB',
        kuota: '5GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: '30GB (8GB + 22GB 4G)',
        harga: '99.520',
        diskon: '',
        productCode: 'sbithreedata4G30GB',
        kuota: '30GB (8GB + 22GB 4G)',
        masaBerlaku: '30 hari',
      },
    ],
  },
  'XL': {
    packages: [
      {
        nama: 'Kuota 4GB Masa aktif 7 Hari',
        harga: '18.000',
        diskon: '',
        productCode: 'sbixldataHR8',
        kuota: '4GB',
        masaBerlaku: '7 hari',
      },
      {
        nama: 'Kuota 3GB Masa aktif 7 Hari',
        harga: '24.180',
        diskon: '',
        productCode: 'sbixldataHR5',
        kuota: '3GB',
        masaBerlaku: '7 hari',
      },
      {
        nama: 'Kuota 1,5GB Masa aktif 30 Hari',
        harga: '48.760',
        diskon: '',
        productCode: 'sbixldataHR50',
        kuota: '1.5GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'Data 3GB untuk masa aktif 30 Hari',
        harga: '60.320',
        diskon: '',
        productCode: 'sbixldata3gb',
        kuota: '3GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'Data 5GB untuk masa aktif 30 Hari',
        harga: '95.500',
        diskon: '',
        productCode: 'sbixldata5gb',
        kuota: '5GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'Kuota 8GB Masa aktif 30 Hari',
        harga: '126.660',
        diskon: '',
        productCode: 'sbixldataHR130',
        kuota: '8GB',
        masaBerlaku: '30 hari',
      },
      {
        nama: 'Kuota 16GB Masa aktif 30 Hari',
        harga: '214.410',
        diskon: '',
        productCode: 'sbixldataHR220',
        kuota: '16GB',
        masaBerlaku: '30 hari',
      },
    ],
  },
};
